// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcykIsfs4vhqXlyb9CddqKtIblWg06bI',
    appId: '1:460407921033:web:2885b2d026116173722958',
    messagingSenderId: '460407921033',
    projectId: 'connectcall-375b6',
    authDomain: 'connectcall-375b6.firebaseapp.com',
    storageBucket: 'connectcall-375b6.firebasestorage.app',
    measurementId: 'G-FRX4CZPXJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLun-kXti-JGu0XtLMntWxfq-P9ASFhio',
    appId: '1:460407921033:android:003fd5d97afaac19722958',
    messagingSenderId: '460407921033',
    projectId: 'connectcall-375b6',
    storageBucket: 'connectcall-375b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzsxDbObrOF85KOB5aqIrXjWX2YWu__ys',
    appId: '1:460407921033:ios:e28d5d4f743f9176722958',
    messagingSenderId: '460407921033',
    projectId: 'connectcall-375b6',
    storageBucket: 'connectcall-375b6.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEcykIsfs4vhqXlyb9CddqKtIblWg06bI',
    appId: '1:460407921033:web:2bd18e8584cd51a7722958',
    messagingSenderId: '460407921033',
    projectId: 'connectcall-375b6',
    authDomain: 'connectcall-375b6.firebaseapp.com',
    storageBucket: 'connectcall-375b6.firebasestorage.app',
    measurementId: 'G-S98Z4NX698',
  );
}
